name: CI Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  gem-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rake test

  package-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: packages/ruby2js

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: packages/rollup-plugin

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: packages/webpack-loader

    - name: Run tests
      run: bundle exec rake packages:test
