name: CI Test

on:
  schedule:
    - cron: '0 0 * * 5'
  push:
  pull_request:

jobs:
  gem-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rake test

  package-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

    - name: Run tests
      run: bundle exec rake packages:test
